import type { NextApiRequest, NextApiResponse } from "next";
import fs from "node:fs";
import formidable from "formidable";
import { z } from "zod";
import { withRequestId } from "@/lib/middleware/withRequestId";
import { logger } from "@/lib/logger";
import { parseDocx } from "@/lib/services/resolution-cleaner/parseDocx";
import { applyReplacements } from "@/lib/services/resolution-cleaner/replacementEngine";
import { assembleDocx } from "@/lib/services/resolution-cleaner/assembleDocx";
import { validateDocxBuffer } from "@/lib/services/resolution-cleaner/validateDocx";
import type {
  ChangeLogEntry,
  ConfirmedTerms,
  ServiceResult,
} from "@/modules/resolution-cleaner/types/resolutionData";

export const config = {
  api: {
    bodyParser: false,
  },
};

const confirmedReplacementsSchema = z.array(
  z.object({
    // Deterministic IDs are generated by detection logic and are not UUID-bound.
    group_id: z.string().min(1).max(128),
    original_value: z.string().min(1),
    new_value: z.string().min(1),
    confirmed_occurrence_offsets: z.array(
      z.object({
        start: z.number().int().min(0),
        end: z.number().int().min(0),
      }),
    ),
    term_key: z
      .enum([
        "borrower_name",
        "lender_name",
        "bond_counsel_name",
        "series_name",
        "unit_count_total",
        "dated_date",
      ])
      .nullable(),
  }),
);

function parseForm(req: NextApiRequest) {
  const form = formidable({
    maxFileSize: 10 * 1024 * 1024,
    multiples: false,
  });

  return new Promise<{ fields: formidable.Fields; files: formidable.Files }>((resolve, reject) => {
    form.parse(req, (error, fields, files) => {
      if (error) {
        reject(error);
        return;
      }
      resolve({ fields, files });
    });
  });
}

function buildConfirmedTerms(changeLog: ChangeLogEntry[]): ConfirmedTerms {
  const terms: ConfirmedTerms = {};
  for (const entry of changeLog) {
    if (entry.term_key === "borrower_name") terms.borrower_name = entry.new_value;
    if (entry.term_key === "lender_name") terms.lender_name = entry.new_value;
    if (entry.term_key === "bond_counsel_name") terms.bond_counsel_name = entry.new_value;
    if (entry.term_key === "series_name") terms.series_name = entry.new_value;
    if (entry.term_key === "unit_count_total") terms.unit_count_total = entry.new_value;
    if (entry.term_key === "dated_date") terms.dated_date = entry.new_value;
  }
  return terms;
}

function hasZipMagic(buffer: Buffer): boolean {
  return (
    buffer.length >= 4 &&
    buffer[0] === 0x50 && // P
    buffer[1] === 0x4b && // K
    [0x03, 0x05, 0x07].includes(buffer[2]) &&
    [0x04, 0x06, 0x08].includes(buffer[3])
  );
}

async function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  if (req.method !== "POST") {
    return res.status(405).json({ success: false, error: "Method not allowed" });
  }

  try {
    const { fields, files } = await parseForm(req);
    const fileItem = Array.isArray(files.file) ? files.file[0] : files.file;
    if (!fileItem) {
      return res.status(400).json({ success: false, error: "No file uploaded" });
    }
    if (!fileItem.originalFilename?.toLowerCase().endsWith(".docx")) {
      return res.status(400).json({ success: false, error: "Only .docx files are supported" });
    }

    const confirmedReplacementsRaw = Array.isArray(fields.confirmedReplacements)
      ? fields.confirmedReplacements[0]
      : fields.confirmedReplacements;
    if (typeof confirmedReplacementsRaw !== "string") {
      return res.status(400).json({ success: false, error: "Missing confirmed replacements" });
    }

    let parsedReplacements: unknown;
    try {
      parsedReplacements = JSON.parse(confirmedReplacementsRaw);
    } catch {
      return res.status(400).json({ success: false, error: "confirmedReplacements must be valid JSON" });
    }

    const replacementsValidation = confirmedReplacementsSchema.safeParse(parsedReplacements);
    if (!replacementsValidation.success) {
      return res.status(400).json({ success: false, error: "Invalid confirmed replacements payload" });
    }

    const confirmedReplacements = replacementsValidation.data;
    const fileBuffer = fs.readFileSync(fileItem.filepath);
    const parsed = parseDocx(fileBuffer);
    const { modifiedXmlString, actualReplacementCounts } = applyReplacements(
      parsed.runs,
      parsed.xmlString,
      parsed.flatText,
      confirmedReplacements,
    );

    const updatedBuffer = assembleDocx(parsed.rawZip, modifiedXmlString);
    if (!hasZipMagic(updatedBuffer)) {
      logger.error("DOCX output missing ZIP magic header");
      return res.status(500).json({
        success: false,
        error: "Generated DOCX is not a valid ZIP container",
      } satisfies ServiceResult<never>);
    }
    const validationResult = validateDocxBuffer(updatedBuffer);
    if (!validationResult.valid) {
      logger.error("DOCX validation failed after replacement", {
        error: validationResult.error,
      });
      return res.status(500).json({
        success: false,
        error: validationResult.error ?? "Generated DOCX failed validation",
      } satisfies ServiceResult<never>);
    }
    const timestamp = new Date().toISOString();

    const changeLog: ChangeLogEntry[] = confirmedReplacements.map((entry) => ({
      original_value: entry.original_value,
      new_value: entry.new_value,
      replacement_count: actualReplacementCounts[entry.group_id] ?? 0,
      term_key: entry.term_key,
      timestamp,
    }));

    const confirmedTerms = buildConfirmedTerms(changeLog);

    logger.info("Replacements applied", {
      groupCount: confirmedReplacements.length,
      totalOccurrences: changeLog.reduce((sum, item) => sum + item.replacement_count, 0),
    });

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    );
    res.setHeader("Content-Transfer-Encoding", "binary");
    res.setHeader("Content-Disposition", 'attachment; filename="resolution_updated.docx"');
    res.setHeader("Content-Length", String(updatedBuffer.length));
    return res.status(200).send(updatedBuffer);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Replacement failed";
    logger.error("Replacement failed", { error: message });
    return res.status(409).json({ success: false, error: message });
  }
}

export default withRequestId(handler);

